name: Build and Test FDW

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out steampipe-postgres-fdw
        uses: actions/checkout@v2
        with:
          repository: "turbot/steampipe-postgres-fdw"
          ref: standalone

      - name: Build steampipe-postgres-fdw
        run: |
          pwd
          ls -ltr
          make standalone plugin_alias="aws" plugin_github_url="github.com/turbot/steampipe-plugin-aws/aws"
          ls -ltr
          
